language: scala
scala: 2.12.10
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "kJ8CXoZ0HMhKk3GALgqn7sS0ZiHKczFkJB6KP74UVwdPaj4geJlBlg8aATzcvTEMQnJ9P0u5suaw2Rjg8yMLa3hQya5jxwnYh2rzP6pTeFVafgjlBtlvG9MIL+slR8NuJH8QctFnFJsN8w83mC6Gheu9/Blpopt8L+Tmw36NaeQfDTQyuNhcIqWLx/UlkHaV9HGx2Snbou7zH55JGhpUN5ftbl9d+Gfc3UP5f/MucS7vBEunAeMCiu0ur58OYOQ96YY058lKy5karF4JahFOinCkJHbynwopbMLr9OoBi5lK3+nTHlW+ckqVcTj4EUzBm+GCB2hzwjk9Q/0WyTyr57goJNF7ZaUjlQGO8kFX/f1AqfS2q1tpwWGvCwKAK+9IsspeixSe63eWliTATTiixvbiMw3ZQBnJyv28LGLfV+rqHqg+JxpJ3TAhHqEXyUQhvYCkesQuofLQEKmejGPq86CItU7mB8RcZqDbYXKbzDcgE/a07/VcLo64IzNQNrqZULVVl/8cRsVxXAanip6yy2rPae+doBlxpCMepGXCIZsq+kTgCwQh/XweqTDmU3pwX42mLn7E+T7pWUPLtOKOyBvuVIzpVFqNcejZdp1m8tNXze6zA46hjlYPqJlz35iCXyvhY6RAICDSL6U2XKXYKaDB244hKkKA7J3PXYbNizA="
    # GITHUB_TOKEN
    - secure: "FVUVJvAdKcecSHHktdzglXDfC+zrEx3NddXJMbT/4n9tYXJBE4Q+2FgwzY5hZ/L9BMNGuPUoDgZbtqTctR5BqDw9eYX7wO08kA8wokIo2Iro/rtBi6dQTxRKBWggVHbjgN1UdzVYQ/Fpew4XV5tTlgrbpTmosF724MUGSvXIn1Wi2VGsDsj5aiMsYrYMiZu7cjJqJEjJ0r1o5sqkeY0EGZ45zwiLi4vE0gRLJPYsvrpuUBQkZ3HM9MctwSnDZaAdgmzRPrdOkfpvkQwh0MAMXNz01qpZUWWSZe245YPMXdmV9/fvWu5oVa3bspy61QT/ht7TVItkS2xKxZnck1cTRJoTEaUSVpw2lDG0prVqeP5KbXV4CrKsU4m4DX8cROBxh2x6G/sD01UFvLssfxQgJSDzAg70Aomxh2fDyh7adcMahw/rE+gTDBgZUjQ2Wssk9Cs9hsrLr1c06EnVzYW5BQ7KOTQ03KDEzR2QDr2F4ufMX4retjh8r//8BQDfPfR1sY4+Q3LFDsjHyCOTsig9CEQ1DUCUlTXGisC3xFQDYbYk17/ehxGzACWGGZq28TmSIkOX5DtWTHgvgnITfDb2Km9rt2A9bcOyfi7xCvoRiY6YRNi7F5MH4A5AKRxAESkkpH4hmuJCkjG+nwwGWld5JvM/sZiC+wz0iu8MY0h4Obk="
    # GITHUB_ACCESS_TOKEN
    - secure: "JRTjKxf+M4HJZc/s7Gm0iMmvQQUJNjvxE4qAbMrqwot4nwomTaofnb8ns3vS4XVq/RqZDrlLd3dCTrPgBb1NUzq7mBy2UOBxUElySF/j4vyzBnDD9mB3oIz78TS9FKOikt5A6x9AuSQOWWMZ1JcRHb4svp6/EI65uIwEgDz+wkru5ZZH+QvNYylR88jTTci4/lgHM6lE2+gzztSEao7KLCTWas2galDhYsVvGcp7j82Xv5XVy1LviOCj7t2yiMil5QnXITsIb4x1gYAsLBSFC1Bdq53kT/h025rdxTtAlcHc7f1At7oVRo4NpVbb3MV3hndbwweZdpWYtk//CTXWzNy1Euv0d19WVtNjdXArZQobbW1NK0kyh7WDUnY4XITUKbfJMrdJWbEKL6IgVlAK9sgIGW7QCpZWiKu5PLn+KMRh8eMAKeEspHGDAfEviQjxIvEEz8CGHnPWm1uNpavaUygjaxlvJNBfK+8ZKuwqCqZR/EqA1LWvQYfFJj+YFpbKoLPruPTZF00ZnLauq3Pb+C3D0fTRRw+qbBdoodkRywmOP/YBEnbeweb9RWXUDZBm4JKMofVEAk5gjTFH3phx4nIdRDwaF+OYyhHYgeCVFsiW1juvlwquNGShVwu8JW5HeqG5ujZBVKMP870ffLxoaK4m9lqwr1UqnzRzluqc150="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "h/dWf3FldpfXqL8T+YCDk6HVKrGvi10DlJTvlfFkzAtlD7f3yjB7k07cnyF1WikUcyg+9xNbl8Jm15RpIdUfg+dbpeaWLH5yoZhI218HcRfra8FPz5cCd/djtzUjr69kN6XOGd4mnKT2vFakoZioA0ZVQS0DZCeAFLgZh3Fdup2xyY8sySghlJCA+uIvOYSitAgJWcDlIAJ8Dt4ZeCAYatKK+Rj6e3C1Gqvy/YWGBCmfNaU33aeZtl9SXMOTzbfQttL15CG7FREqlfCDdW6+aznnBMj5gi2MN7PpMfdCuN9XFbuIuPyzDt8aTspWinClSBRLEWgsElm14LIhZZHluXUcqWq9qPbpAfYxLGP03qhi7CR88iS5NzqAFOE4oiS9DEye4lkvGcw+IXUkfHeP1JXMenJ8KDkHonhRS+OtwMT12d2IvBO8KCruloaW9Pbu6wb4Wvl7uHfyYI5GxsDrKbxNpL+qFbo2+YRcHRGql/LJEpvDtx1E2Vzp8rQJ8X0P05l7BZredOzvbCMU/0pkJKex42xN9+j20sz/SUyJcZq7nTPlMaS4BrFulKIpPH9y48sE3TX26encFw174DGOouqITLI1DFKyZ5PwjH3s0Oj0xGQC7rx77GiaDCBn8j99MAFSOY2GA4M/IWjVKcIehwfmY6nmhv9+q5p4AjIP24E="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-snowflake';
        bumpInDownstream() { echo $1 > slamdata-destination-snowflake-version; }
        export -f bumpInDownstream
        scripts/bumpDependentProject slamdata slamx bumpInDownstream
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
